version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000 
      - DB_NAME=jira_pet_project 
      - DB_USER=postgres 
      - DB_PASSWORD=rootroot 
      - DB_HOST=postgres 
      - DB_PORT=5432 
      - SECRET_KEY=secret_key_jira_pet_project
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: jira_pet_project
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
